# -*- coding: utf-8 -*-
"""request.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DQoT5ZtAy_Id8IxATMFxQFZb0PE4Ix-n
"""

python server.py