# -*- coding: utf-8 -*-
"""server.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oSZfqDop3D04IdTWcWz9dwh8WZ9q8CzX
"""

import os
import pandas as pd 
import numpy as np 
from flask import Flask, request, jsonify
import pickle
from flask import Flask, render_template, request
app=Flask(__name__)
@app.route('/')
def index():
 return flask.render_template('index.html')

def ValuePredictor(to_predict_list):
 to_predict = np.array(to_predict_list).reshape(1,4)
 loaded_model = pickle.load(open('model.pkl','rb'))
 result = loaded_model.predict(to_predict)
 return predict[0]
 
@app.route('/predict',methods = ['POST'])
def predict():
  if request.method == 'POST':
    to_predict_list = request.form.to_dict()
    to_predict_list = list(to_predict_list.values())
    to_predict_list = list(map(float, to_predict_list))
    result = ValuePredictor(to_predict_list)
    prediction = str(result)
    return render_template("predict.html", prediction = prediction)
 
  if __name__ == '__main__':
    app.run(port=5000,debug=True)